### PR TITLE
Update to a pre-release upstream using the Plugin Framework

### PR DESCRIPTION
**Pull request by t0yv0**
Upstream version: f3a69cbc0904

On top of https://github.com/pulumi/pulumi-random/pull/263

This is the second attempt to update Random to the latest-greatest pre-release version utilizing the Plugin Framework. The previous attempt had to be rolled back because of https://github.com/pulumi/pulumi-random/issues/258, but this is now fixed in pf/tfbridge and covered by test in #263.

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
Looks like a standard upgrade. Trusting that the bridge is solid, this should be too.

**Review by jazzyfresh — APPROVED** [review]

**Comment by t0yv0** [comment]
Trust but verify 🙂

**Comment by AaronFriel** [comment]
The "keepers" breaking change is unfortunate.

**Comment by t0yv0** [comment]
This is the same breaking change we've accepted before. This is an upstream breaking change. I think that programs that use strings there should still be fine.

**Pull request merged**
