### PR TITLE
Update bridge to 3.76.0

### PR DESCRIPTION
**Pull request by EronWright**
This is a routine update, done by hand as the automated one has been failing.

Updates a replay test to address a breaking change (see https://github.com/pulumi/home/issues/3308).

### CODE REVIEW

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-random/blob/master/.ci-mgmt.yaml#L8 this is pinned to 5.x but perhaps time to move to 6.x; looks like your local build environment picked up 6.x

**Comment by EronWright** [comment]
Here's an explanation for how my local environment influenced code generation: `make tfgen` installs plugins into the user home and then the latest is apparently used. I found an effective workaround to be to set `PULUMI_HOME` to `.pulumi`:
```sh
PULUMI_HOME=./.pulumi make tfgen build_sdks
```

**Review by VenelinMartinov — APPROVED** [review]
Looks good, thanks for sorting this out!

**Review by blampe — APPROVED** [review]

**Comment by t0yv0** [comment]
Let's make it official https://github.com/pulumi/ci-mgmt/issues/832

**Pull request merged**
